---
- name: Creates user dir
  file:
    path: /etc/dconf/profile
    state: directory

- name: Delete existing user file
  file:
    path: /etc/dconf/profile/user
    state: absent

- name: Copy dconf profile
  copy: src=dconf/user dest=/etc/dconf/profile/user


- name: Creates db dir
  file:
    path: /etc/dconf/db/local.d
    state: directory

- name: Delete existing config file
  file:
    path: /etc/dconf/db/local.d/01-user
    state: absent

- name: Copy dconf config
  copy: src=dconf/01-user dest=/etc/dconf/db/local.d/01-user

- name: dconf update
  become_user: daniel
  shell: dconf update